# Defines two organizations
#  - Orderer organization
#  - Org1  = Single peer organization
#    Uses the "Specs" to declare the peers instead of Template

##### Orderer for acme

OrdererOrgs:
  - Name: Orderer
    Domain: hospital.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: Hospital

#### Peers for acme
PeerOrgs:
  # Peer configuration for ACME
  - Name: Sms
    Domain: sms.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: doctor
        CommonName: doctor
    Users:
      Count: 2
