# Defines two organizations
#  - Orderer organization
#  - Org1  = Single peer organization
#    Uses the "Specs" to declare the peers instead of Template

##### Orderer for acme
OrdererOrgs:
  - Name: Orderer
    Domain: hospital.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer
  - Name: Orderer
    Domain: hospital2.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: orderer

#### Peers for acme
PeerOrgs:
  # Peer configuration for ACME
  - Name: Hospital1
    Domain: hospital1.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users:
      Count: 2
  - Name: Hospital2
    Domain: hospital2.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users:
      Count: 2
  - Name: Hospital3
    Domain: hospital3.com
    #EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users:
      Count: 2
